config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # 独自定義のルーティング
  root to: 'home#index'

  get  '/new-order/index', to: 'choose_patient_for_new_orders#new', as: 'new_order'
  post '/new-order/index', to: 'choose_patient_for_new_orders#create'

  get  '/login', to: 'employee_sessions#new'
  post '/login', to: 'employee_sessions#create'
  get '/logout', to: 'employee_sessions#destroy'

  get '/orders', to: 'recent_orders#index', as: 'recent_orders'

  get  '/create', to: 'init_organizations#new'
  post '/create', to: 'init_organizations#create'

  # 履歴管理 PaperTrail::Version のためのルーティング
  get 'histories',     to: 'paper_trail/versions#index'
  get 'histories/:id', to: 'paper_trail/versions#show', as: 'history'

  # ajax用RESTfulルーティング
  namespace :ajax do
    resources :select_exam_sets,  only: :new
    resources :select_exam_items, only: %i[index new]
    resources :orders, only: %i[index edit]
    resources :exams,  only: %i[index edit]
  end

  # RESTfulなルーティング
  resources(:organizations, except: :index) do
    resources(:employees, shallow: true)
    resources(:invitations, only: %i[index new create destroy], shallow: true)

    resources(:patients, except: :show, shallow: true) do
      resources(:orders, except: %i[show edit], shallow: true) do
        resources(:exams, except: %i[show edit], shallow: true)
      end
    end
  end

  resources :exam_items, except: :show
  resources :exam_sets,  except: :show
end

app/models/employee.rb
# frozen_string_literal: true

class Employee < ApplicationRecord
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i.freeze

  authenticates_with_sorcery!

  # implement soft delete
  include Discard::Model
  default_scope -> { kept.order(:id) }

  # relations
  belongs_to :organization

  # validation
  validates :fullname, presence: true
  validates :email, uniqueness: true
  validates :email, format: { with: EMAIL_REGEX, message: 'format is invalid' }
  validates :password,
            length: { minimum: 4 },
            if: -> { new_record? || changes[:crypted_password] }
  validates :password,
            confirmation: true,
            length: { minimum: 4 },
            if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation,
            presence: true,
            if: -> { new_record? || changes[:crypted_password] }

  enum role: %i[mere admin]

  # TODO: resource#paper_trail がないものを渡した時のエラーハンドリングを作成（する必要あるかも）
  def self.originator_of(resource)
    select(:fullname).find_by(id: resource.paper_trail.originator)&.fullname || 'Unknown-Employee'
  end
end

app/controllers/employees_controller.rb
# frozen_string_literal: true

class EmployeesController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :no_employee
  skip_before_action :require_login, only: %i[new create]
  before_action :set_organization, only: %i[index new create]
  before_action :verify_token, only: %i[new create]

  def index
    @employees = Employee.accessible_by(current_ability).page(params[:page])
  end

  def show
    @employee = Employee.accessible_by(current_ability).find(params[:id])
  end

  def new
    @employee = @organization.employees.new
  end

  def create
    @employee = @organization.employees.new(create_params)
    if @employee.save
      @invitation.revoke
      login(create_params[:email], create_params[:password])
      flash[:success] = '従業員アカウントを作成しました。'
      redirect_to @employee
    else
      flash.now[:warning] = '正しく入力してください。'
      render :new, status: :bad_request
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.valid_password?(params[:employee][:password]) && @employee.update(update_params)
      flash[:success] = '従業員情報を更新しました。'
      redirect_to @employee
    else
      flash.now[:warning] = '正しく入力してください。'
      render :edit, status: :bad_request
    end
  end

  def destroy
    employee = Employee.find(params[:id])
    employee.discard
    logout
    redirect_to login_url
  end

  private

  def create_params
    params.require(:employee).permit(:fullname, :email, :password, :password_confirmation)
  end

  def update_params
    params.require(:employee).permit(:fullname, :email)
  end

  def set_organization
    @organization = Organization.find_by(id: params[:organization_id])
  end

  def verify_token
    @invitation = Invitation.find_by(token: params[:invitation_token])
    return if @invitation&.organization.present? && @invitation.active?

    flash[:warning] = '該当リンクが正しくないか期限切れです。'
    redirect_to '/create'
  end

  def no_employee
    flash[:warning] = '該当従業員は存在しません。不正なリクエストです。'
    redirect_to organization_employees_path(current_user.organization)
  end
end

app/views/employees/edit.html.slim
= breadcrumb({ text: '従業員一覧', href: organization_employees_path(current_user.organization) },
             { text: @employee.fullname, href: employee_path(@employee) },
             { text: '従業員情報の編集', href: edit_employee_path(@employee) })

.section
  h1.title 従業員情報編集

.section
  .columns
    = form_for @employee, url: employee_url(@employee), html: { class: 'column is-half' } do |f|
      .field.is-horizontal
        .field-label.is-normal
          = f.label :fullname, '氏名', class: 'label'
        .field-body
          .field
            .control
              = f.text_field :fullname, class: 'input'

      .field.is-horizontal
        .field-label.is-normal
          = f.label :email, 'メールアドレス', class: 'label'
        .field-body
          .field
            .control
              = f.text_field :email, class: 'input'

      .field.is-horizontal
        .field-label.is-normal
          = f.label :password, 'パスワード(本人確認)', class: 'label'
        .field-body
          .field
            .control
              = f.password_field :password, class: 'input'

      .field.is-horizontal
        .field-label.is-normal
        .field-body
          .field
            .control
              = f.submit '更新',
                  class: 'button is-primary has-text-weight-bold',
                  'data-controller': 'components--submitbtn',
                  'data-action': 'components--submitbtn#click'
              = link_to '従業員リストへ戻る', organization_employees_path(current_user.organization), class: 'button is-text is-pulled-right'

.section
  .columns
    .column.is-half.control
      = button_to '削除', employee_path(@employee.id), method: :delete, class: 'button is-danger has-text-weight-bold is-pulled-right',
        'data-controller': 'components--confirmbtn', 'data-action': 'components--confirmbtn#click'

app/views/employees/index.html.slim
= breadcrumb({ text: '従業員一覧', href: organization_employees_path(current_user.organization) })

.section
  h1.title 従業員一覧

.section
  table.table.is-hoverable
    thead
      tr
        th 従業員ID
        th 従業員名
    tbody
      - @employees.each do |employee|
        tr
          th= employee.id
          td= link_to employee.fullname, employee_path(employee.id)

.section
  = paginate @employees, theme: 'bulma'

app/views/employees/new.html.slim
= breadcrumb({ text: '従業員一覧', href: organization_employees_path(@organization) },
             { text: '従業員新規登録', href: new_organization_employee_path(@organization) })

.section
  h1.title 従業員新規登録

.section
  .columns
    = form_for @employee, url: organization_employees_path(@organization, invitation_token: @invitation.token), html: { class: 'column is-half' } do |f|
      .field.is-horizontal
        .field-label.is-normal
          = f.label :fullname, '氏名', class: 'label'
        .field-body
          .field
            .control
              = f.text_field :fullname, class: 'input'

      .field.is-horizontal
        .field-label.is-normal
          = f.label :email, 'メールアドレス', class: 'label'
        .field-body
          .field
            .control
              = f.text_field :email, class: 'input'

      .field.is-horizontal
        .field-label.is-normal
          = f.label :password, 'パスワード', class: 'label'
        .field-body
          .field
            .control
              = f.password_field :password, class: 'input'

      .field.is-horizontal
        .field-label.is-normal
          = f.label :password_confirmation, 'パスワード(確認)', class: 'label'
        .field-body
          .field
            .control
              = f.password_field :password_confirmation, class: 'input'

      .field.is-horizontal
        .field-label.is-normal
        .field-body
          .field
            .control
              = f.submit '登録',
                  class: 'button is-primary has-text-weight-bold',
                  'data-controller': 'components--submitbtn',
                  'data-action': 'components--submitbtn#click'

app/views/employees/show.html.slim
= breadcrumb({ text: '従業員一覧', href: organization_employees_path(current_user.organization) },
             { text: @employee.fullname, href: employee_path(@employee.id) })

.section
  h1.title #{@employee.fullname} のページ
  - if current_user == @employee
    p= link_to '従業員情報の編集', edit_employee_path(@employee), class: 'button is-info has-text-weight-bold'