config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # 独自定義のルーティング
  root to: 'home#index'

  get  '/new-order/index', to: 'choose_patient_for_new_orders#new', as: 'new_order'
  post '/new-order/index', to: 'choose_patient_for_new_orders#create'

  get  '/login', to: 'employee_sessions#new'
  post '/login', to: 'employee_sessions#create'
  get '/logout', to: 'employee_sessions#destroy'

  get '/orders', to: 'recent_orders#index', as: 'recent_orders'

  get  '/create', to: 'init_organizations#new'
  post '/create', to: 'init_organizations#create'

  # 履歴管理 PaperTrail::Version のためのルーティング
  get 'histories',     to: 'paper_trail/versions#index'
  get 'histories/:id', to: 'paper_trail/versions#show', as: 'history'

  # ajax用RESTfulルーティング
  namespace :ajax do
    resources :select_exam_sets,  only: :new
    resources :select_exam_items, only: %i[index new]
    resources :orders, only: %i[index edit]
    resources :exams,  only: %i[index edit]
  end

  # RESTfulなルーティング
  resources(:organizations, except: :index) do
    resources(:employees, shallow: true)
    resources(:invitations, only: %i[index new create destroy], shallow: true)

    resources(:patients, except: :show, shallow: true) do
      resources(:orders, except: %i[show edit], shallow: true) do
        resources(:exams, except: %i[show edit], shallow: true)
      end
    end
  end

  resources :exam_items, except: :show
  resources :exam_sets,  except: :show
end

app/models/exam_item.rb
# frozen_string_literal: true

class ExamItem < ApplicationRecord
  # implement soft delete
  include Discard::Model
  default_scope -> { kept.order(:id) }

  has_paper_trail

  # Declare relation
  has_and_belongs_to_many :exam_sets, join_table: 'combinations'
  has_many :exams

  # Declare validation
  validates :formal_name, presence: true
end

app/controllers/ajax/exam_items_controller.rb
# frozen_string_literal: true

class Ajax::ExamItemsController < ApplicationController
  def index
    @exam_items =
      if params[:exam_set_id].blank?
        ExamItem.all
      else
        ExamSet.find_by(id: params[:exam_set_id]).exam_items
      end
    render layout: false
  end
end

app/controllers/exam_items_controller.rb
# frozen_string_literal: true

class ExamItemsController < ApplicationController
  before_action :set_exam_datas, only: %i[new create edit update]

  def index
    @exam_items = ExamItem.page(params[:page])
  end

  def new
    @exam_item = ExamItem.new
  end

  def create
    @exam_item = ExamItem.new(exam_item_params)
    if @exam_item.save
      flash[:success] = "検査詳細 #{@exam_item.formal_name} を作成しました。"
      redirect_to exam_items_path
    else
      render :new, status: :bad_request
    end
  end

  def edit
    @exam_item = ExamItem.find_by(id: params[:id])
  end

  def update
    @exam_item = ExamItem.find_by(id: params[:id])
    if @exam_item.update(exam_item_params)
      redirect_to exam_item_path(@exam_item)
    else
      render :edit, status: :bad_request
    end
  end

  def destroy
    exam_item = ExamItem.find_by(id: params[:id])
    exam_item.paper_trail_event = 'discard'
    exam_item.discard
    flash[:success] = '検査詳細情報を削除しました。'
    redirect_to exam_items_path
  end

  private

  def exam_item_params
    params
      .require(:exam_item)
      .permit(:formal_name, :abbreviation, exam_set_ids: [])
  end

  def set_exam_datas
    @exam_items = ExamItem.all
    @exam_sets  = ExamSet.all
  end
end

app/views/exam_items/edit.html.slim
= breadcrumb({ text: '検査詳細一覧', href: exam_items_path },
             { text: "#{@exam_item.formal_name} の編集", href: edit_exam_item_path(@exam_item) })

.section
  h1.title 検査詳細 編集
  p.is-size-6
  | 各項目を入力してください。
  | 検査詳細を検査セットに含めさせたい場合、「検査セット」より含めさせる先のセットを選択してください。

.section
  = render 'forms/select_exam_sets', resource_field: 'exam_item[exam_sets][]'

  = form_for @exam_item, url: exam_items_url do |f|
    .field.is-grouped.is-grouped-multiline#selected-exams
      / 編集対象の検査詳細を含んでいる検査セットを表示する
      / 内容は ajax/select_exam_sets/new とほぼ同等
      - @exam_item.exam_sets.each do |exam_set|
        .control data-controller='components--removebtn'
          .tags.has-addons
            span.tag.is-medium
              = exam_set.name
              a.delete.is.small data-action='components--removebtn#click'
          = hidden_field_tag 'exam_item[exam_sets][]', exam_set.id, id: "selected-exam-#{exam_set.id}"

    .columns
      .column.is-8
        .field.is-horizontal
          .field-label.is-normal
            = f.label :formal_name, '名称', class: 'label'
          .field-body
            .field
              .control
                = f.text_field :formal_name, class: 'input'

        .field.is-horizontal
          .field-label.is-normal
            = f.label :abbreviation, '略称 (任意)', class: 'label'
          .field-body
            .field
              .control
                = f.text_field :abbreviation, class: 'input'

        .field.is-horizontal
          .field-body
            .field
              .control
                button.button.is-primary.has-text-weight-bold(type='submit' data-controller='components--submitbtn' data-action='components--submitbtn#click')
                  | 更新
                = link_to '検査詳細一覧に戻る', exam_items_path, class: 'button is-text is-pulled-right'

  .columns
    .column.is-8
      .control
        = button_to '削除',
          exam_item_path(@exam_item),
          method: :delete,
          class: 'button is-danger has-text-weight-bold is-pulled-right',
          'data-controller': 'components--confirmbtn',
          'data-action': 'components--confirmbtn#click'

app/views/exam_items/index.html.slim
= breadcrumb({ text: '検査詳細一覧', href: exam_items_path })

.section
  h1.title 検査詳細一覧
  p= link_to '新規作成', new_exam_item_path, class: 'button is-primary has-text-weight-bold'

.section
  table.table.is-hoverable
    thead
      tr
        th 検査詳細名
        th 略称
        th 編集
    tbody
      - @exam_items.each do |exam_item|
        tr
          td= exam_item.formal_name
          td= exam_item.abbreviation
          td= link_to '編集', edit_exam_item_path(exam_item.id)

.section
  = paginate @exam_items, theme: 'bulma'

app/views/exam_items/new.html.slim
= breadcrumb({ text: '検査詳細一覧', href: exam_items_path },
             { text: '新規作成', href: new_exam_item_path })

.section
  h1.title 検査詳細 新規作成
  p.is-size-6
  | 各項目を入力してください。
  | 検査詳細を検査セットに含めさせたい場合、「検査セット」より含めさせる先のセットを選択してください。

.section
  = render 'forms/select_exam_sets', resource_field: 'exam_item[exam_set_ids][]'

  = form_for @exam_item, url: exam_items_url do |f|
    .field.is-grouped.is-grouped-multiline#selected-exams

    .columns
      .column.is-8
        .field.is-horizontal
          .field-label.is-normal
            = f.label :formal_name, '名称', class: 'label'
          .field-body
            .field
              .control
                = f.text_field :formal_name, class: 'input'

        .field.is-horizontal
          .field-label.is-normal
            = f.label :abbreviation, '略称 (任意)', class: 'label'
          .field-body
            .field
              .control
                = f.text_field :abbreviation, class: 'input'

    .field.is-horizontal
      .field-body
        .field
          .control
            button.button.is-primary.has-text-weight-bold(type='submit' data-controller='components--submitbtn' data-action='components--submitbtn#click')
              | 作成