config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # 独自定義のルーティング
  root to: 'home#index'

  get  '/new-order/index', to: 'choose_patient_for_new_orders#new', as: 'new_order'
  post '/new-order/index', to: 'choose_patient_for_new_orders#create'

  get  '/login', to: 'employee_sessions#new'
  post '/login', to: 'employee_sessions#create'
  get '/logout', to: 'employee_sessions#destroy'

  get '/orders', to: 'recent_orders#index', as: 'recent_orders'

  get  '/create', to: 'init_organizations#new'
  post '/create', to: 'init_organizations#create'

  # 履歴管理 PaperTrail::Version のためのルーティング
  get 'histories',     to: 'paper_trail/versions#index'
  get 'histories/:id', to: 'paper_trail/versions#show', as: 'history'

  # ajax用RESTfulルーティング
  namespace :ajax do
    resources :select_exam_sets,  only: :new
    resources :select_exam_items, only: %i[index new]
    resources :orders, only: %i[index edit]
    resources :exams,  only: %i[index edit]
  end

  # RESTfulなルーティング
  resources(:organizations, except: :index) do
    resources(:employees, shallow: true)
    resources(:invitations, only: %i[index new create destroy], shallow: true)

    resources(:patients, except: :show, shallow: true) do
      resources(:orders, except: %i[show edit], shallow: true) do
        resources(:exams, except: %i[show edit], shallow: true)
      end
    end
  end

  resources :exam_items, except: :show
  resources :exam_sets,  except: :show
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  # implement soft delete
  include Discard::Model
  default_scope -> { kept.order(:id) }

  has_paper_trail

  enum status: %i[in_progress done]

  # callbacks
  after_discard do
    exams.update_all(discarded_at: discarded_at)
  end

  # validations
  validates :canceled, inclusion: { in: [true, false] }
  validates :status, presence: true

  # relations
  belongs_to :patient
  has_many :exams, dependent: :destroy

  scope :recently_created, -> { where(canceled: false).includes(:patient).last(20) }

  def exams_with_detail
    exams.includes(:exam_item)
  end

  def exams_only_active
    exams_with_detail.where(canceled: false)
  end

  def canceled?
    canceled
  end

  def may_result_at_to_s
    may_result_at ? may_result_at.to_formatted_s(:simple) : '未定'
  end
end

app/controllers/ajax/exam_items_controller.rb
# frozen_string_literal: true

class Ajax::ExamItemsController < ApplicationController
  def index
    @exam_items =
      if params[:exam_set_id].blank?
        ExamItem.all
      else
        ExamSet.find_by(id: params[:exam_set_id]).exam_items
      end
    render layout: false
  end
end

app/controllers/ajax/exams_controller.rb
# frozen_string_literal: true

class Ajax::ExamsController < ApplicationController
  def index
    @order = Order.find_by(id: params[:order_id])

    @exams =
      if params[:canceled].to_i.zero?
        @order.exams_only_active.page(params[:page])
      else
        @order.exams_with_detail.page(params[:page])
      end
    render layout: false
  end

  def edit
    @exam = Exam.find_by(id: params[:id])
    @originator = Employee.originator_of(@exam)
    render layout: false
  end
end

app/controllers/ajax/orders_controller.rb
# frozen_string_literal: true

class Ajax::OrdersController < ApplicationController
  def index
    @patient = Patient.find_by(id: params[:patient_id])

    @orders =
      if params[:canceled].to_i.zero?
        @patient.orders_only_active.page(params[:page])
      else
        @patient.orders.page(params[:page])
      end
    render layout: false
  end

  def edit
    @order = Order.find_by(id: params[:id])
    @originator = Employee.originator_of(@order)
    render layout: false
  end
end

app/controllers/ajax/select_exam_items_controller.rb
# frozen_string_literal: true

class Ajax::SelectExamItemsController < ApplicationController
  def index
    @exam_items =
      if params[:exam_set_id].blank?
        ExamItem.all
      else
        ExamSet.find_by(id: params[:exam_set_id]).exam_items
      end
    render layout: false
  end

  def new
    @exam_items = ExamItem.where(id: params[:exam_item_ids])
    @resource_field = params[:resource_field]
    render layout: false
  end
end

app/controllers/ajax/select_exam_sets_controller.rb
# frozen_string_literal: true

class Ajax::SelectExamSetsController < ApplicationController
  def new
    @exam_sets = ExamSet.where(id: params[:exam_set_ids])
    @resource_field = params[:resource_field]
    render layout: false
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :set_patient, only: %i[index new create]
  before_action :set_for_new, only: %i[new create]

  def index
    @page   = params[:page] || 1
    @orders = @patient.orders_only_active.page(params[:page])
  end

  def new; end

  def create
    if create_params[:exam_item_ids].nil?
      flash.now[:warning] = '検査項目は必ず指定してください。'
      render :new, status: :bad_request
      return
    end

    @order = @patient.orders.create!(may_result_at: create_params[:may_result_at])
    timestamp = Time.now
    insert_datas = create_params[:exam_item_ids].map do |exam_item_id|
      {
        order_id: @order.id,
        exam_item_id: exam_item_id,
        created_at: timestamp,
        updated_at: timestamp
      }
    end
    Exam.insert_all!(insert_datas)

    flash[:success] = "オーダー##{@order.id}を作成しました。"
    CreateNotificationService.call(notification_type: :order_created, order: @order)
    redirect_to order_exams_path(@order)
  end

  def update
    @order = Order.accessible_by(current_ability).find_by(id: params[:id])
    @order.update(update_params)

    flash[:success] = '更新しました。'
    CreateNotificationService.call(notification_type: :order_updated, order: @order)
    redirect_to patient_orders_path(@order.patient)
  end

  def destroy
    order = Order.accessible_by(current_ability).find_by(id: params[:id])
    order.paper_trail_event = 'discard'
    order.discard
    flash[:success] = '該当オーダー情報を削除しました。'
    redirect_to patient_orders_url(order.patient.id)
  end

  private

  # 検査が1つも選択されなかった場合、再度 'new' アクションの描画を行う必要があります。
  #
  # 'render' メソッドは、 **同じアクション内で別のテンプレートを描画する** ため、
  # 'create' アクション内で「不正なフォーム送信」として再度 'render' した場合、
  # 検査の分類 (@set) と検査 (@details) が未定義となり、正しく動作しません
  # 'new, create' 両方のアクションにこれらの代入宣言を加えれば良いのですが、
  # DRYに反するということ、記述量の増加という点からメソッドとしてまとめ、
  # 'before_action' にフックしています。
  def set_for_new
    @order      = @patient.orders.new
    @exam_sets  = ExamSet.all
    @exam_items = ExamItem.all
  end

  def set_patient
    @patient = Patient.accessible_by(current_ability).find_by(id: params[:patient_id])
  end

  def create_params
    params.require(:order).permit(:may_result_at, exam_item_ids: [])
  end

  def update_params
    params.require(:order).permit(:canceled, :may_result_at)
  end
end

app/views/ajax/orders/edit.html.slim
.modal.is-active(data-controller='components--removebtn')
  .modal-background(data-action='click->components--removebtn#click')
  .modal-card
    .modal-card-head
      h1.is-size-4 オーダー##{@order.id} の編集

    .modal-card-body
      .tags.has-addons
        span.tag.is-medium.is-info 最終更新
        span.tag.is-medium #{@order.updated_at.to_formatted_s(:abs_datetime)} #{@originator}

      = form_for @order, url: order_path do |f|
        .field.is-horizontal
          .field-label.is-normal
            = f.label :may_result_at, '時間診察日', class: 'label'
          .field-body
            .field
              .control
                = f.date_field :may_result_at, min: Time.zone.now

        .field.is-horizontal
          .field-label.is-normal
            = f.label :canceled, 'キャンセル', class: 'label'
          .field-body
            .field
              .control
                = f.check_box :canceled

        .field
          p.control
            button.button.is-primary.has-text-weight-bold(type='submit' data-controller='components--submitbtn' data-action='components--submitbtn#click')
              | 更新
            button.button.is-text.is-pulled-right(data-action='components--removebtn#click')
              | オーダーリストへ戻る

      .control
        = button_to '削除', order_path(@order.id), method: :delete, class: 'button is-danger has-text-weight-bold is-pulled-right',
          'data-controller': 'components--confirmbtn', 'data-action': 'components--confirmbtn#click'

  button.modal-close.is-large(aria-label='close' data-action='components--removebtn#click')

app/views/ajax/orders/index.html.slim
- @orders.each do |order|
  tr(class="#{order.canceled? ? 'has-text-dark has-background-grey-light' : ''}")
    th= order.id
    td= link_to "オーダー##{order.id}", order_exams_path(order.id)
    td= order.may_result_at_to_s
    td= order.status
    td
      a(data-controller='ajax--orders' data-action='ajax--orders#edit' data-ajax--orders-id="#{order.id}")
        | 編集