config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # 独自定義のルーティング
  root to: 'home#index'

  get  '/new-order/index', to: 'choose_patient_for_new_orders#new', as: 'new_order'
  post '/new-order/index', to: 'choose_patient_for_new_orders#create'

  get  '/login', to: 'employee_sessions#new'
  post '/login', to: 'employee_sessions#create'
  get '/logout', to: 'employee_sessions#destroy'

  get '/orders', to: 'recent_orders#index', as: 'recent_orders'

  get  '/create', to: 'init_organizations#new'
  post '/create', to: 'init_organizations#create'

  # 履歴管理 PaperTrail::Version のためのルーティング
  get 'histories',     to: 'paper_trail/versions#index'
  get 'histories/:id', to: 'paper_trail/versions#show', as: 'history'

  # ajax用RESTfulルーティング
  namespace :ajax do
    resources :select_exam_sets,  only: :new
    resources :select_exam_items, only: %i[index new]
    resources :orders, only: %i[index edit]
    resources :exams,  only: %i[index edit]
  end

  # RESTfulなルーティング
  resources(:organizations, except: :index) do
    resources(:employees, shallow: true)
    resources(:invitations, only: %i[index new create destroy], shallow: true)

    resources(:patients, except: :show, shallow: true) do
      resources(:orders, except: %i[show edit], shallow: true) do
        resources(:exams, except: %i[show edit], shallow: true)
      end
    end
  end

  resources :exam_items, except: :show
  resources :exam_sets,  except: :show
end

app/models/exam.rb
# frozen_string_literal: true

class Exam < ApplicationRecord
  # implement soft delete
  include Discard::Model
  default_scope -> { kept.order(:id) }

  has_paper_trail

  enum status: %i[unbooked booked sampled unresulted resulted appraised]

  # Declare callback
  before_save :amend_status

  # Declare validation
  validates :urgent, :canceled, :submitted, inclusion: { in: [true, false] }
  validates :status, presence: true

  # Declare relation
  belongs_to :order
  belongs_to :exam_item

  delegate :formal_name, to: :exam_item
  delegate :abbreviation, to: :exam_item

  def urgent?
    urgent
  end

  def canceled?
    canceled
  end

  def submitted?
    submitted
  end

  def booked_at_to_s
    booked_at ? booked_at.to_formatted_s(:simple) : '未定'
  end

  def sample_to_s
    sample.blank? ? '未取得' : sample
  end

  def result_to_s
    result.blank? ? '未取得' : result
  end

  def appraisal_to_s
    appraisal.blank? ? '未取得' : appraisal
  end

  private

  def amend_status
    self.status =
      if    !appraisal.blank? then :appraised
      elsif !result.blank?    then :resulted
      elsif !sample.blank? &&  submitted? then :unresulted
      elsif !sample.blank? && !submitted? then :sampled
      elsif !booked_at.nil?   then :booked
      else :unbooked
      end
  end
end

app/models/exam_set.rb
# frozen_string_literal: true

class ExamSet < ApplicationRecord
  # implement soft delete
  include Discard::Model
  default_scope -> { kept.order(:id) }

  has_paper_trail

  # Declare relation
  has_and_belongs_to_many :exam_items, join_table: 'combinations'

  # Declare validation
  validates :name, presence: true
end

app/controllers/ajax/exams_controller.rb
# frozen_string_literal: true

class Ajax::ExamsController < ApplicationController
  def index
    @order = Order.find_by(id: params[:order_id])

    @exams =
      if params[:canceled].to_i.zero?
        @order.exams_only_active.page(params[:page])
      else
        @order.exams_with_detail.page(params[:page])
      end
    render layout: false
  end

  def edit
    @exam = Exam.find_by(id: params[:id])
    @originator = Employee.originator_of(@exam)
    render layout: false
  end
end

app/controllers/exams_controller.rb
# frozen_string_literal: true

class ExamsController < ApplicationController
  before_action :set_order,   only: %i[index create new]
  before_action :set_for_new, only: %i[new create]

  def index
    @page  = params[:page] || 1
    @exams = @order.exams_only_active.page(params[:page])
  end

  def new; end

  # アクション名としては 'create' ですが、
  # 操作的には該当オーダーへの 'add' なので、注意してください
  def create
    if create_params[:exam_item_ids].nil?
      flash.now[:warning] = '検査項目は必ず指定してください。'
      render :new, status: :bad_request
      return
    end

    timestamp = Time.now
    insert_datas = create_params[:exam_item_ids].map do |exam_item_id|
      {
        order_id: @order.id,
        exam_item_id: exam_item_id,
        created_at: timestamp,
        updated_at: timestamp
      }
    end
    Exam.insert_all!(insert_datas)

    flash[:success] = '検査項目を追加しました。'
    CreateNotificationService.call(notification_type: :exam_added, order: @order)
    redirect_to order_exams_path(@order)
  end

  def update
    @exam = Exam.accessible_by(current_ability).find_by(id: params[:id])
    @exam.update(update_params)

    flash[:success] = '更新しました。'
    CreateNotificationService.call(notification_type: :exam_updated, order: @exam.order)
    redirect_to order_exams_url(@exam.order)
  end

  def destroy
    exam = Exam.accessible_by(current_ability).find_by(id: params[:id])
    exam.paper_trail_event = 'discard'
    exam.discard
    flash[:success] = '該当検査情報を削除しました。'
    redirect_to order_exams_url(exam.order.id)
  end

  private

  # 詳細については `OrdersController#set_for_new` を参照してください。
  def set_for_new
    @exam = @order.exams.new
    @exam_sets  = ExamSet.all
    @exam_items = ExamItem.all
  end

  def set_order
    @order = Order.accessible_by(current_ability).find_by(id: params[:order_id])
  end

  def create_params
    params.require(:order).permit(exam_item_ids: [])
  end

  def update_params
    params
      .require(:exam)
      .permit(:status_id, :urgent, :canceled, :submitted, :sample, :result, :appraisal, :booked_at)
  end
end

app/views/exams/index.html.slim
- if @order.canceled?
  .message.is-warning
    .message-body
      p このオーダーはキャンセルされています。

= breadcrumb({ text: '患者一覧', href: organization_patients_path(current_user.organization) },
             { text: @order.patient.name, href: patient_orders_path(@order.patient.id) },
             { text: "オーダー##{@order.id}", href: order_exams_path(@order.id) })

.section
  h1.title オーダー##{@order.id} 検査リスト
  p= link_to "オーダー##{@order.id}の検査を追加", new_order_exam_path(@order.id), class: 'button is-primary has-text-weight-bold'

.section
  .field.is-horizontal
    .field-label.is-normal
      label.label.has-text-weight-normal キャンセル済みを
    .field-body
      .field
        .control
          .select
            = select_tag 'canceled', options_for_select({'非表示' => 0, '表示' => 1}),
              'data-controller': 'ajax--exams',
              'data-action': 'ajax--exams#index',
              'data-ajax--exams-order-id': @order.id,
              'data-ajax--exams-page': @page

.section
  table.table.is-hoverable
    thead
      tr
        th 検査名
        th 状態
        th 採取予定日
        th 検体情報
        th 結果
        th 評価
        th 編集
    tbody#exams-listup
      = render template: 'ajax/exams/index'

.section
  = paginate @exams, theme: 'bulma'

.section#exam-edit-modal

app/views/exams/new.html.slim
= breadcrumb({ text: '患者一覧', href: organization_patients_path(current_user.organization) },
             { text: @order.patient.name, href: patient_orders_path(@order.patient.id) },
             { text: "オーダー##{@order.id}", href: order_exams_path(@order.id) },
             { text: '検査の追加', href: '#' })

.section
  h1.title オーダー##{@order.id} 検査項目追加
  p.is-size-6 追加する検査項目を選択してください。

.section
  = render 'forms/select_exam_items', resource_field: 'order[exam_item_ids][]'

  = form_for @exam, url: order_exams_path do |f|
    / to avoid params[:order] will be empty
    = hidden_field_tag 'order[empty]'

    .field.is-grouped.is-grouped-multiline#selected-exams

    .field
      p
        button.button.is-primary.has-text-weight-bold(type='submit' data-controller='components--submitbtn' data-action='components--submitbtn#click')
          | 追加
        = link_to "オーダー##{@order.id}の検査一覧へ", order_exams_path(@order.patient), class: 'button is-text is-pulled-right'